#!/bin/bash
SCRIPT_DIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
FILES_DIR="$SCRIPT_DIR/files/"
PROJECT_DIR=$(pwd)/
PROJECT_NAME="placeholder"
LICENSE="mit"
MESSAGE="placeholder"

while [[ $# -gt 0 ]]; do
	case "$1" in
		-n) PROJECT_NAME="$2"; shift 2;;
		-l) LICENSE="$2"; shift 2;;
		-m) MESSAGE="$2"; shift 2;;
		*) echo "[Rogue] invalid arguments"; return 1;;
	esac
done
GREEN="\e[32m"
RESET="\e[0m"

gh api "/licenses/$LICENSE" --jq .body > "$PROJECT_DIR/LICENSE"
echo -e "${GREEN}[✔]${RESET} Created LICENSE"

cat <<EOL > "$PROJECT_DIR/README.md"
Project_Name:  "$PROJECT_NAME";<br>
Commit message: "$MESSAGE"
<br>
<br>
This is automatically generated by RoguePM
React project.
EOL
echo -e "${GREEN}[✔]${RESET} Created README.md"

cat <<EOL > "$PROJECT_DIR/package.json"
{
  "name": "$PROJECT_NAME",
  "version": "0.1.0",
  "description": "Generated by RoguePM",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "tsc && vite build",
    "preview": "vite preview"
  }
}
EOL
echo -e "${GREEN}[✔]${RESET} Created package.json"

cat <<EOL > "$PROJECT_DIR/tsconfig.json"
{
  "compilerOptions": {
    "target": "ES2020",
    "useDefineForClassFields": true,
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "skipLibCheck": true,
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "isolatedModules": true,
    "moduleDetection": "force",
    "noEmit": true,
    "jsx": "react-jsx",
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true
  },
  "include": ["src"]
}
EOL
echo -e "${GREEN}[✔]${RESET} Created tsconfig.json"

mkdir -p "$PROJECT_DIR/src"

cat <<EOL > "$PROJECT_DIR/index.html"
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>$PROJECT_NAME</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
EOL
echo -e "${GREEN}[✔]${RESET} Created index.html"

cat <<EOL > "$PROJECT_DIR/src/App.tsx"
function App() {
  return <h1>Hello, $PROJECT_NAME!</h1>
}

export default App
EOL
echo -e "${GREEN}[✔]${RESET} Created src/App.tsx"

if [ -d "$FILES_DIR" ]; then
	shopt -s dotglob
	for item in "$FILES_DIR"*; do
		if [ -f "$item" ]; then
			cp "$item" "$PROJECT_DIR/"
			echo -e "${GREEN}[✔]${RESET} Created $(basename "$item")"
		elif [ -d "$item" ]; then
			cp -r "$item" "$PROJECT_DIR/"
			echo -e "${GREEN}[✔]${RESET} Created $(basename "$item") directory"
		fi
	done
	shopt -u dotglob
else
	echo "[Rogue] Additional files not found, skipping..."
fi
