#!/bin/bash
SCRIPT_DIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
FILES_DIR="$SCRIPT_DIR/files/"
PROJECT_DIR=$(pwd)/
PROJECT_NAME="placeholder"
LICENSE="mit"
MESSAGE="placeholder"

while [[ $# -gt 0 ]]; do
	case "$1" in
		-n) PROJECT_NAME="$2"; shift 2;;
		-l) LICENSE="$2"; shift 2;;
		-m) MESSAGE="$2"; shift 2;;
		*) echo "[Rogue] invalid arguments"; return 1;;
	esac
done
GREEN="\e[32m"
RESET="\e[0m"

gh api "/licenses/$LICENSE" --jq .body > "$PROJECT_DIR/LICENSE"
echo -e "${GREEN}[✔]${RESET} Created LICENSE"

cat <<EOL > "$PROJECT_DIR/README.md"
Project_Name:  "$PROJECT_NAME";<br>
Commit message: "$MESSAGE"
<br>
<br>
This is automatically generated by RoguePM
Verilog project.
EOL
echo -e "${GREEN}[✔]${RESET} Created README.md"

mkdir -p "$PROJECT_DIR/src" "$PROJECT_DIR/tb"

cat <<EOL > "$PROJECT_DIR/src/${PROJECT_NAME}.v"
module $PROJECT_NAME (
    input  wire clk,
    input  wire rst_n,
    output reg  done
);

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n)
            done <= 1'b0;
        else
            done <= 1'b1;
    end

endmodule
EOL
echo -e "${GREEN}[✔]${RESET} Created src/${PROJECT_NAME}.v"

cat <<EOL > "$PROJECT_DIR/tb/${PROJECT_NAME}_tb.v"
\`timescale 1ns / 1ps

module ${PROJECT_NAME}_tb;

    reg  clk;
    reg  rst_n;
    wire done;

    ${PROJECT_NAME} uut (
        .clk(clk),
        .rst_n(rst_n),
        .done(done)
    );

    initial begin
        clk = 0;
        forever #5 clk = ~clk;
    end

    initial begin
        rst_n = 0;
        #20 rst_n = 1;
        #100 \$finish;
    end

    initial begin
        \$dumpfile("${PROJECT_NAME}.vcd");
        \$dumpvars(0, ${PROJECT_NAME}_tb);
    end

endmodule
EOL
echo -e "${GREEN}[✔]${RESET} Created tb/${PROJECT_NAME}_tb.v"

if [ -d "$FILES_DIR" ]; then
	shopt -s dotglob
	for item in "$FILES_DIR"*; do
		if [ -f "$item" ]; then
			cp "$item" "$PROJECT_DIR/"
			echo -e "${GREEN}[✔]${RESET} Created $(basename "$item")"
		elif [ -d "$item" ]; then
			cp -r "$item" "$PROJECT_DIR/"
			echo -e "${GREEN}[✔]${RESET} Created $(basename "$item") directory"
		fi
	done
	shopt -u dotglob
else
	echo "[Rogue] Additional files not found, skipping..."
fi
