# ==========================================
# MODULE: NEW (PROJECT)
# ==========================================

cmd_new() {
    if [[ "$1" == "session" ]]; then
        shift; cmd_new_session "$@"; return $?
    fi

    local replace="false"
    local create_local="false"
    local prompt_desc="false"
    local target_remote=""
    local project_name=""
    local visibility="private"
    local commit_msg="Initial commit"
    local desc_msg="Generated by RoguePM"
    local license="mit"
    local template="default"

    while [[ $# -gt 0 ]]; do
        case "$1" in
            -r|--replace) replace="true"; shift ;;
            --local) create_local="true"; shift ;;
            -v|--visibility)
                if [[ "$2" != "public" && "$2" != "private" ]]; then
                    log_error "Visibility must be 'public' or 'private'."
                    return 1
                fi
                visibility="$2"
                shift 2 ;;
            --remote)
                if [[ "$2" != "github" && "$2" != "gitlab" && "$2" != "both" ]]; then
                    log_error "--remote must be 'github', 'gitlab', or 'both'."
                    return 1
                fi
                target_remote="$2"
                shift 2 ;;
            -t|--template)
                if [[ -z "$2" || "$2" == -* ]]; then
                    template=""
                else
                    if [[ -d "$TEMPLATES_DIR/$2" ]]; then
                        template="$2"
                    else
                        log_error "Template does not exist. Using default template."
                        template="default"
                    fi
                    shift
                fi
                shift ;;
            -m|--message)
                [ -z "$2" ] && { log_error "Commit message cannot be empty."; return 1; }
                commit_msg="$2"
                shift 2 ;;
            -d|--description)
                prompt_desc="true"
                shift 1 ;;
            -l|--license)
                if [[ -z "$2" || "$2" == -* ]]; then
                    license="mit"; shift 1
                else
                    license="$2"; shift 2
                fi ;;
            --help|-h)
                echo -e "\n${ROGUE_RED_ITALIC}[Rogue]${RESET} ${BOLD}NEW COMMAND USAGE${RESET}"
                echo -e "source rogue new [project_name] [options]\n"
                echo -e "  session       Create an interactive session.sh (run 'rogue new session')"
                echo -e "  -r                  Replace existing directory if it exists"
                echo -e "  --local             Create project in current working directory"
                echo -e "  --remote <target>   Target platform: 'github', 'gitlab', or 'both'"
                echo -e "  -v <public|private> Set repository visibility (default is private)"
                echo -e "  -t [template]       Use a template, or omit name for fzf picker"
                echo -e "  -m <message>        Initial commit message"
                echo -e "  -d, --description   Prompt for a cloud repository description"
                return 0 ;;
            *)
                if [[ -z "$project_name" && "$1" != -* ]]; then
                    project_name="$1"
                else
                    log_error "Invalid flag for 'new': $1"; return 1
                fi
                shift ;;
        esac
    done

    [ -z "$project_name" ] && log_prompt "Enter project name: " project_name

    if [ "$prompt_desc" == "true" ]; then
        local user_desc
        log_prompt "Enter repository description: " user_desc
        [ -n "$user_desc" ] && desc_msg="$user_desc"
    fi

    if [ -z "$template" ]; then
        if ! command -v fzf &> /dev/null; then
            log_error "'fzf' is not installed. Using default template."
            template="default"
        else
            local template_list=()
            for dir in "$TEMPLATES_DIR"/*/; do
                [ -d "$dir" ] && template_list+=("$(basename "$dir")")
            done
            if [ ${#template_list[@]} -gt 0 ]; then
                local selected
                selected=$(printf "%s\n" "${template_list[@]}" | fzf --prompt="[Rogue] Select template > " --height=40% --border=rounded)
                if [ -n "$selected" ]; then
                    template="$selected"
                else
                    template="default"
                fi
            else
                template="default"
            fi
        fi
    fi

    local auth_failed="false"
    if [[ "$target_remote" == "github" || "$target_remote" == "both" ]]; then
        check_github_auth || auth_failed="true"
    fi
    if [[ "$target_remote" == "gitlab" || "$target_remote" == "both" ]]; then
        check_gitlab_auth || auth_failed="true"
    fi

    if [ "$auth_failed" == "true" ]; then
        local fallback_choice
        log_prompt "Continue with local folder setup only? (y/n): " fallback_choice
        if [[ "$fallback_choice" =~ ^[Yy]$ ]]; then
            log_info "Proceeding with local setup. (Skipping remote creation)"
            target_remote=""
        else
            log_info "Aborting project creation safely. No files were created."
            return 1
        fi
    fi

    log_divider "--- Provisioning Workspace ---"

    if [ "$create_local" == "true" ]; then
        local target_dir="$PWD/$project_name"
        echo "$target_dir" >> "$LOCAL_PROJECTS_LIST"
        awk '!seen[$0]++' "$LOCAL_PROJECTS_LIST" > "${LOCAL_PROJECTS_LIST}.tmp" && mv "${LOCAL_PROJECTS_LIST}.tmp" "$LOCAL_PROJECTS_LIST"
    else
        local target_dir="$PROJECTS_DIR/$project_name"
    fi

    if [ -d "$target_dir" ]; then
        if [ "$replace" == "true" ]; then
            log_info "Replacing existing directory..."
            rm -rf "$target_dir"
            mkdir -p "$target_dir"
        else
            log_error "Directory already exists! Use -r to replace it."
            return 1
        fi
    else
        log_info "Creating project folder..."
        mkdir -p "$target_dir"
    fi

    cd "$target_dir" || return 1
    echo "$target_dir" > /tmp/.rogue_cd

    log_info "Initializing git repository..."
    git init

    log_info "Creating template files..."
    local template_script="$TEMPLATES_DIR/$template/$template.sh"
    if [ -x "$template_script" ]; then
        "$template_script" -n "$project_name" -l "$license" -m "$commit_msg"
    else
        log_error "Template script missing/not executable at: $template_script"
    fi

    log_info "Staging and committing initial files..."
    git add .
    git commit -m "$commit_msg"

    if [[ -n "$target_remote" ]]; then
        log_divider "--- Provisioning Cloud Remotes ---"

        if [[ "$target_remote" == "github" || "$target_remote" == "both" ]]; then
            log_info "Creating GitHub repository ($visibility)..."
            gh repo create "$project_name" --"$visibility" --description "$desc_msg"
            local gh_user=$(gh api user --jq .login)
            git remote add github "https://github.com/$gh_user/$project_name.git"
            log_info "Pushing to GitHub..."
            git push -u github master
        fi

        if [[ "$target_remote" == "gitlab" || "$target_remote" == "both" ]]; then
            log_info "Creating GitLab repository ($visibility)..."
            glab repo create "$project_name" --"$visibility" --description "$desc_msg"
            local gl_user=$(glab api user -q '.username')
            git remote add gitlab "https://gitlab.com/$gl_user/$project_name.git"
            log_info "Pushing to GitLab..."
            git push -u gitlab master
        fi
    fi

    log_success "Project online: $project_name"

    local create_sesh
    log_prompt "Create session.sh for this project? (y/N): " create_sesh
    if [[ "$create_sesh" =~ ^[Yy]$ ]]; then
        cmd_new_session "$project_name" "$target_dir"
    fi
}
