# ==========================================
# MODULE: NEW (PROJECT)
# ==========================================

cmd_new() {
    if [[ "$1" == "session" ]]; then
        shift; cmd_new_session "$@"; return $?
    fi

    local replace="false"
    local create_local="false"
    local prompt_desc="false"
    local target_remote=""
    local project_name=""
    local target_ws=""
    local visibility="private"
    local commit_msg="Initial commit"
    local desc_msg="Generated by RoguePM"
    local license="mit"
    local template="default"

    while [[ $# -gt 0 ]]; do
        case "$1" in
            -r|--replace) replace="true"; shift ;;
            --local) create_local="true"; shift ;;
            -w|--ws|--workspace)
                [ -z "$2" ] || [[ "$2" == -* ]] && { log_error "--ws requires a workspace name"; return 1; }
                target_ws="$2"; shift 2 ;;
            -n|--name)
                [ -z "$2" ] || [[ "$2" == -* ]] && { log_error "--name requires a project name"; return 1; }
                project_name="$2"; shift 2 ;;
            -v|--visibility)
                if [[ "$2" != "public" && "$2" != "private" ]]; then
                    log_error "Visibility must be 'public' or 'private'."
                    return 1
                fi
                visibility="$2"
                shift 2 ;;
            --remote)
                if [[ "$2" != "github" && "$2" != "gitlab" && "$2" != "both" ]]; then
                    log_error "--remote must be 'github', 'gitlab', or 'both'."
                    return 1
                fi
                target_remote="$2"
                shift 2 ;;
            -t|--template)
                if [[ -z "$2" || "$2" == -* ]]; then
                    template=""
                else
                    template="$2"
                    shift
                fi
                shift ;;
            -m|--message)
                [ -z "$2" ] && { log_error "Commit message cannot be empty."; return 1; }
                commit_msg="$2"
                shift 2 ;;
            -d|--description)
                if [[ -n "$2" && "$2" != -* ]]; then
                    desc_msg="$2"
                    shift 2
                else
                    prompt_desc="true"
                    shift 1
                fi ;;
            -l|--license)
                if [[ -z "$2" || "$2" == -* ]]; then
                    license="mit"; shift 1
                else
                    license="$2"; shift 2
                fi ;;
            --help|-h)
                echo -e "\n${ROGUE_RED_ITALIC}[Rogue]${RESET} ${BOLD}NEW COMMAND USAGE${RESET}"
                echo -e "source rogue new [project_name] [options]\n"
                echo -e "  session             Create an interactive session.sh (run 'rogue new session')"
                echo -e "  -n, --name <name>   Project name"
                echo -e "  -w, --ws <name>     Target workspace / organization"
                echo -e "  -r, --replace       Replace existing directory if it exists"
                echo -e "  --local             Create project in current working directory"
                echo -e "  --remote <target>   Target platform: 'github', 'gitlab', or 'both'"
                echo -e "  -v <public|private> Set repository visibility (default is private)"
                echo -e "  -t [template]       Use a template, or omit name for picker"
                echo -e "  -m <message>        Initial commit message"
                echo -e "  -d, --description   Repository description"
                echo -e "  -l, --license       License type (default: mit)\n"
                return 0 ;;
            *)
                if [[ -z "$project_name" && "$1" != -* ]]; then
                    project_name="$1"
                else
                    log_error "Invalid flag for 'new': $1"; return 1
                fi
                shift ;;
        esac
    done

    # Fuzzy resolve target workspace if provided
    if [ -n "$target_ws" ]; then
        local resolved_ws
        resolved_ws=$(resolve_workspace_name "$target_ws") || return 1
        target_ws="$resolved_ws"
    fi

    # Fuzzy resolve template if provided
    if [ -n "$template" ]; then
        local resolved_tpl
        resolved_tpl=$(resolve_template_name "$template") || return 1
        template="$resolved_tpl"
    fi

    local json_file="${ROGUE_CONFIG:-$HOME/.config/rogue/rogueConf.json}"
    local ws_path=""
    local ws_gh_org=""
    local ws_git_email=""

    # Lookup target workspace settings if specified
    if [ -n "$target_ws" ] && [ -f "$json_file" ] && command -v jq &>/dev/null; then
        local ws_data
        ws_data=$(jq --arg name "$target_ws" '.workspaces[]? | select(.name == $name)' "$json_file" 2>/dev/null)
        if [ -n "$ws_data" ] && [ "$ws_data" != "null" ]; then
            ws_path=$(echo "$ws_data" | jq -r '.path')
            ws_path="${ws_path/#\~/$HOME}"
            ws_gh_org=$(echo "$ws_data" | jq -r '.gh_org // empty')
            ws_git_email=$(echo "$ws_data" | jq -r '.git_user_email // empty')
        else
            log_error "Workspace '$target_ws' not found in configuration."
            return 1
        fi
    fi

    [ -z "$project_name" ] && log_prompt "Enter project name: " project_name
    [ -z "$project_name" ] && { log_error "Project name cannot be empty."; return 1; }

    if [ "$prompt_desc" == "true" ]; then
        local user_desc
        log_prompt "Enter repository description: " user_desc
        [ -n "$user_desc" ] && desc_msg="$user_desc"
    fi

    [ -z "$template" ] && template="default"

    local auth_failed="false"
    if [[ "$target_remote" == "github" || "$target_remote" == "both" ]]; then
        check_github_auth || auth_failed="true"
    fi
    if [[ "$target_remote" == "gitlab" || "$target_remote" == "both" ]]; then
        check_gitlab_auth || auth_failed="true"
    fi

    if [ "$auth_failed" == "true" ]; then
        local fallback_choice
        log_prompt "Continue with local folder setup only? (y/n): " fallback_choice
        if [[ "$fallback_choice" =~ ^[Yy]$ ]]; then
            log_info "Proceeding with local setup. (Skipping remote creation)"
            target_remote=""
        else
            log_info "Aborting project creation safely. No files were created."
            return 1
        fi
    fi

    echo -e "\n────────────────────────────────────────────"
    echo -e "${ROGUE_RED_ITALIC}[Rogue]${RESET} ${BOLD_ITALIC_UNDERLINE}Provisioning Workspace${RESET}\n"

    local target_dir=""
    if [ "$create_local" == "true" ]; then
        target_dir="$PWD/$project_name"
        local list_file="${LOCAL_PROJECTS_LIST:-$HOME/.config/rogue/rp.list}"
        mkdir -p "$(dirname "$list_file")"
        local rp_entry="$target_dir"
        [ -n "$target_ws" ] && rp_entry="$target_dir|$target_ws"
        echo "$rp_entry" >> "$list_file"
        awk '!seen[$0]++' "$list_file" > "${list_file}.tmp" && mv "${list_file}.tmp" "$list_file"
    elif [ -n "$ws_path" ]; then
        mkdir -p "$ws_path"
        target_dir="$ws_path/$project_name"
    else
        target_dir="$PROJECTS_DIR/$project_name"
    fi

    if [ -d "$target_dir" ]; then
        if [ "$replace" == "true" ]; then
            log_step "Replacing existing directory..."
            rm -rf "$target_dir"
            mkdir -p "$target_dir"
        else
            log_error "Directory already exists: $target_dir! Use -r to replace it."
            return 1
        fi
    else
        log_step "Creating project folder..."
        mkdir -p "$target_dir"
    fi

    cd "$target_dir" || return 1
    echo "$target_dir" > /tmp/.rogue_cd

    log_step "Initializing git repository..."
    git init

    if [ -n "$ws_git_email" ]; then
        git config user.email "$ws_git_email"
        log_step "Configured git user.email: $ws_git_email"
    fi

    log_step "Creating template files..."
    local template_script="$TEMPLATES_DIR/$template/$template.sh"
    if [ -x "$template_script" ]; then
        "$template_script" -n "$project_name" -l "$license" -m "$commit_msg"
    else
        log_error "Template script missing/not executable at: $template_script"
    fi

    log_step "Staging and committing initial files..."
    git add .
    git commit -m "$commit_msg"

    if command -v tree &> /dev/null; then
        echo -e "\n${ROSE_PINE_GOLD}$(tree -L 1 --dirsfirst --color=never 2>/dev/null)${RESET}"
    fi

    if [[ -n "$target_remote" ]]; then
        echo -e "\n────────────────────────────────────────────"
        echo -e "${ROGUE_RED_ITALIC}[Rogue]${RESET} ${BOLD_ITALIC_UNDERLINE}Provisioning Cloud Remotes${RESET}\n"

        if [[ "$target_remote" == "github" || "$target_remote" == "both" ]]; then
            if [ -n "$ws_gh_org" ]; then
                log_step "Creating GitHub repository under organization '$ws_gh_org' ($visibility)..."
                gh repo create "$ws_gh_org/$project_name" --"$visibility" --description "$desc_msg"
                git remote add github "https://github.com/$ws_gh_org/$project_name.git"
            else
                log_step "Creating GitHub repository ($visibility)..."
                gh repo create "$project_name" --"$visibility" --description "$desc_msg"
                local gh_user=$(gh api user --jq .login)
                git remote add github "https://github.com/$gh_user/$project_name.git"
            fi
            log_step "Pushing to GitHub..."
            git push -u github master
        fi

        if [[ "$target_remote" == "gitlab" || "$target_remote" == "both" ]]; then
            log_step "Creating GitLab repository ($visibility)..."
            glab repo create "$project_name" --"$visibility" --description "$desc_msg"
            local gl_user=$(glab api user -q '.username')
            git remote add gitlab "https://gitlab.com/$gl_user/$project_name.git"
            log_step "Pushing to GitLab..."
            git push -u gitlab master
        fi
    fi

    echo -e "\n────────────────────────────────────────────"
    log_success "Project initialized: $project_name"

    local create_sesh
    log_prompt "Create session.sh for this project? (y/N): " create_sesh
    if [[ "$create_sesh" =~ ^[Yy]$ ]]; then
        cmd_new_session "$project_name" "$target_dir"
    fi
}
