#!/bin/bash
SCRIPT_DIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
FILES_DIR="$SCRIPT_DIR/files/"
PROJECT_DIR=$(pwd)/
PROJECT_NAME="placeholder"
LICENSE="mit"
MESSAGE="placeholder"

while [[ $# -gt 0 ]]; do
	case "$1" in
		-n) PROJECT_NAME="$2"; shift 2;;
		-l) LICENSE="$2"; shift 2;;
		-m) MESSAGE="$2"; shift 2;;
		*) echo "[Rogue] invalid arguments"; return 1;;
	esac
done
GREEN="\e[32m"
RESET="\e[0m"

gh api "/licenses/$LICENSE" --jq .body > "$PROJECT_DIR/LICENSE"
echo -e "${GREEN}[✔]${RESET} Created LICENSE"

cat <<EOL > "$PROJECT_DIR/README.md"
Project_Name:  "$PROJECT_NAME";<br>
Commit message: "$MESSAGE"
<br>
<br>
This is automatically generated by RoguePM
EOL
echo -e "${GREEN}[✔]${RESET} Created README.md"

mkdir -p "$PROJECT_DIR/$PROJECT_NAME"

cat <<EOL > "$PROJECT_DIR/$PROJECT_NAME/__init__.py"
# $PROJECT_NAME package
EOL
echo -e "${GREEN}[✔]${RESET} Created $PROJECT_NAME/__init__.py"

cat <<EOL > "$PROJECT_DIR/$PROJECT_NAME/main.py"
def main():
    print("Hello, $PROJECT_NAME!")


if __name__ == "__main__":
    main()
EOL
echo -e "${GREEN}[✔]${RESET} Created $PROJECT_NAME/main.py"

cat <<EOL > "$PROJECT_DIR/requirements.txt"
# Dependencies
EOL
echo -e "${GREEN}[✔]${RESET} Created requirements.txt"

cat <<EOL > "$PROJECT_DIR/pyproject.toml"
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "$PROJECT_NAME"
version = "0.1.0"
description = "Generated by RoguePM"
requires-python = ">=3.8"

[project.scripts]
$PROJECT_NAME = "$PROJECT_NAME.main:main"
EOL
echo -e "${GREEN}[✔]${RESET} Created pyproject.toml"

if [ -d "$FILES_DIR" ]; then
	shopt -s dotglob
	for item in "$FILES_DIR"*; do
		if [ -f "$item" ]; then
			cp "$item" "$PROJECT_DIR/"
			echo -e "${GREEN}[✔]${RESET} Created $(basename "$item")"
		elif [ -d "$item" ]; then
			cp -r "$item" "$PROJECT_DIR/"
			echo -e "${GREEN}[✔]${RESET} Created $(basename "$item") directory"
		fi
	done
	shopt -u dotglob
else
	echo "[Rogue] Additional files not found, skipping..."
fi
