#!/bin/bash
SCRIPT_DIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
FILES_DIR="$SCRIPT_DIR/files/"
PROJECT_DIR=$(pwd)/
PROJECT_NAME="placeholder"
LICENSE="mit"
MESSAGE="placeholder"

while [[ $# -gt 0 ]]; do
	case "$1" in
		-n) PROJECT_NAME="$2"; shift 2;;
		-l) LICENSE="$2"; shift 2;;
		-m) MESSAGE="$2"; shift 2;;
		*) echo "[Rogue] invalid arguments"; return 1;;
	esac
done

gh api "/licenses/$LICENSE" --jq .body > "$PROJECT_DIR/LICENSE"
echo "[✔] Created LICENSE"

cat <<EOL > "$PROJECT_DIR/README.md"
Project_Name:  "$PROJECT_NAME";<br>
Commit message: "$MESSAGE"
<br>
<br>
This is automatically generated by RoguePM
Discord bot project (TypeScript + discord.js).
EOL
echo "[✔] Created README.md"

mkdir -p "$PROJECT_DIR/src/commands" "$PROJECT_DIR/src/events" "$PROJECT_DIR/config"

cat <<EOL > "$PROJECT_DIR/package.json"
{
  "name": "$PROJECT_NAME",
  "version": "0.1.0",
  "description": "Generated by RoguePM",
  "main": "dist/index.js",
  "scripts": {
    "build": "tsc",
    "start": "node dist/index.js",
    "dev": "tsx watch src/index.ts"
  },
  "dependencies": {
    "discord.js": "^14.0.0"
  },
  "devDependencies": {
    "typescript": "^5.0.0",
    "tsx": "^4.0.0",
    "@types/node": "^20.0.0"
  }
}
EOL
echo "[✔] Created package.json"

cat <<EOL > "$PROJECT_DIR/tsconfig.json"
{
  "compilerOptions": {
    "target": "ES2022",
    "module": "commonjs",
    "lib": ["ES2022"],
    "outDir": "./dist",
    "rootDir": "./src",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "resolveJsonModule": true
  },
  "include": ["src"]
}
EOL
echo "[✔] Created tsconfig.json"

cat <<EOL > "$PROJECT_DIR/.env.example"
DISCORD_TOKEN=your_bot_token_here
EOL
echo "[✔] Created .env.example"

cat <<EOL > "$PROJECT_DIR/config/config.json"
{
  "client": {
    "token": "",
    "intents": ["Guilds", "GuildMessages", "MessageContent"]
  }
}
EOL
echo "[✔] Created config/config.json"

cat <<EOL > "$PROJECT_DIR/src/index.ts"
import { Client, Events, GatewayIntentBits } from "discord.js";
import config from "../config/config.json";
import { handlePing } from "./commands/ping";
import { handleHelp } from "./commands/help";
import { handleMention } from "./events/onMention";

const client = new Client({
  intents: [
    GatewayIntentBits.Guilds,
    GatewayIntentBits.GuildMessages,
    GatewayIntentBits.MessageContent,
  ],
});

client.once(Events.ClientReady, (c) => {
  console.log(\`\${c.user.username} is online.\`);
});

client.on(Events.MessageCreate, (message) => {
  if (message.author.bot) return;
  handlePing(message);
  handleHelp(message);
  handleMention(client, message);
});

client.login(config.client.token);
EOL
echo "[✔] Created src/index.ts"

cat <<EOL > "$PROJECT_DIR/src/commands/ping.ts"
import { Message } from "discord.js";

export function handlePing(message: Message): void {
  if (message.content === "!ping") {
    message.reply("Pong!");
    console.log(\`User \${message.author.username} used !ping\`);
  }
}
EOL
echo "[✔] Created src/commands/ping.ts"

cat <<EOL > "$PROJECT_DIR/src/commands/help.ts"
import { Message } from "discord.js";

export function handleHelp(message: Message): void {
  if (message.content === "!help") {
    message.reply("Available commands: !ping, !help");
    console.log(\`User \${message.author.username} used !help\`);
  }
}
EOL
echo "[✔] Created src/commands/help.ts"

cat <<EOL > "$PROJECT_DIR/src/events/onMention.ts"
import { Client, Message } from "discord.js";

export function handleMention(client: Client, message: Message): void {
  if (message.mentions.has(client.user!) && !message.author.bot) {
    message.reply("Hey! Need help? Type '!help'");
    console.log(\`User \${message.author.username} mentioned this bot\`);
  }
}
EOL
echo "[✔] Created src/events/onMention.ts"

if [ -d "$FILES_DIR" ]; then
	shopt -s dotglob
	for item in "$FILES_DIR"*; do
		if [ -f "$item" ]; then
			cp "$item" "$PROJECT_DIR/"
			echo "[✔] Created $(basename "$item")"
		elif [ -d "$item" ]; then
			cp -r "$item" "$PROJECT_DIR/"
			echo "[✔] Created $(basename "$item") directory"
		fi
	done
	shopt -u dotglob
else
	echo "[Rogue] Additional files not found, skipping..."
fi
