#!/bin/bash
SCRIPT_DIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
FILES_DIR="$SCRIPT_DIR/files/"
PROJECT_DIR=$(pwd)/
PROJECT_NAME="placeholder"
LICENSE="mit"
MESSAGE="placeholder"

#Parse arguments
while [[ $# -gt 0 ]]; do 
	case "$1" in
		-n) PROJECT_NAME="$2"; shift 2;;
		-l) LICENSE="$2"; shift 2;;
		-m) MESSAGE="$2"; shift 2;;
		*) echo -e "\e[1m[Rogue]\e[0m invalid arguments"; return 1;; # throws when arguments other than the above two is passed
	esac
done
GREEN="\e[32m"
RESET="\e[0m"

gh api "/licenses/$LICENSE" --jq .body > "$PROJECT_DIR/LICENSE"
echo -e "${GREEN}[✔]${RESET} Created LICENSE"

cat <<EOL > "$PROJECT_DIR/README.md"
Project_Name:  "$PROJECT_NAME";<br> 
Commit message: "$MESSAGE"
<br>
<br>
This is automatically generated by RoguePM
Descriptions for the repository will be updated in the future commits
EOL
echo -e "${GREEN}[✔]${RESET} Created README.md"

touch "$PROJECT_DIR/$PROJECT_NAME.circ"
echo -e "${GREEN}[✔]${RESET} Created $PROJECT_NAME.circ"

# Debug stuffs
# echo "Checking directory: $FILES_DIR"
# ls -l "$FILES_DIR"  # List contents for debugging

# Create predefined files and directories
if [ -d "$FILES_DIR" ];then
	shopt -s dotglob
	for item in "$FILES_DIR"*;do
		# echo $item # Debug stuffs
		if [ -f "$item" ];then
			cp "$item" "$PROJECT_DIR/"
			echo -e "${GREEN}[✔]${RESET} Created $(basename "$item")" 
		elif [ -d "$item" ];then
			cp -r "$item" "$PROJECT_DIR/"
			echo -e "${GREEN}[✔]${RESET} Created $(basename "$item") directory" 
		fi
	done
	shopt -u dotglob
elif [ ! -d "$FILES_DIR" ];then
	echo -e "\e[1m[Rogue]\e[0m Additional files not found, skipping....."
	return 1
else
	echo -e "\e[1m[Rogue]\e[0m yeah something fishy this shouldn't happen"
fi

