#!/bin/bash
SCRIPT_DIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
FILES_DIR="$SCRIPT_DIR/files/"
PROJECT_DIR=$(pwd)/
PROJECT_NAME="placeholder"
LICENSE="mit"
MESSAGE="placeholder"

while [[ $# -gt 0 ]]; do
	case "$1" in
		-n) PROJECT_NAME="$2"; shift 2;;
		-l) LICENSE="$2"; shift 2;;
		-m) MESSAGE="$2"; shift 2;;
		*) echo -e "\e[1m[Rogue]\e[0m invalid arguments"; return 1;;
	esac
done

gh api "/licenses/$LICENSE" --jq .body > "$PROJECT_DIR/LICENSE"
echo "[✔] Created LICENSE"

cat <<EOL > "$PROJECT_DIR/README.md"
Project_Name:  "$PROJECT_NAME";<br>
Commit message: "$MESSAGE"
<br>
<br>
This is automatically generated by RoguePM
Descriptions for the repository will be updated in the future commits
EOL
echo "[✔] Created README.md"

if [ -d "$FILES_DIR" ]; then
	cp "$FILES_DIR/sketch.ino" "$PROJECT_DIR/$PROJECT_NAME.ino"
	echo "[✔] Created $PROJECT_NAME.ino"
	cp "$FILES_DIR/config.h" "$PROJECT_DIR/config.h"
	echo "[✔] Created config.h"

	shopt -s dotglob
	for item in "$FILES_DIR"*; do
		if [ -f "$item" ]; then
			cp "$item" "$PROJECT_DIR/"
			echo "[✔] Created $(basename "$item")"
		elif [ -d "$item" ]; then
			cp -r "$item" "$PROJECT_DIR/"
			echo "[✔] Created $(basename "$item") directory"
		fi
	done
	shopt -u dotglob

	rm -f "$PROJECT_DIR/sketch.ino"
elif [ ! -d "$FILES_DIR" ]; then
	echo "[Rogue] Additional files not found, skipping....."
	return 1
else
	echo "[Rogue] yeah something fishy this shouldn't happen"
fi
