#!/bin/bash
SCRIPT_DIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
FILES_DIR="$SCRIPT_DIR/files/"
PROJECT_DIR=$(pwd)/
PROJECT_NAME="placeholder"
LICENSE="mit"
MESSAGE="placeholder"

while [[ $# -gt 0 ]]; do
	case "$1" in
		-n) PROJECT_NAME="$2"; shift 2;;
		-l) LICENSE="$2"; shift 2;;
		-m) MESSAGE="$2"; shift 2;;
		*) echo "[Rogue] invalid arguments"; return 1;;
	esac
done
GREEN="\e[32m"
RESET="\e[0m"

gh api "/licenses/$LICENSE" --jq .body > "$PROJECT_DIR/LICENSE"
echo -e "${GREEN}[✔]${RESET} Created LICENSE"

cat <<EOL > "$PROJECT_DIR/README.md"
Project_Name:  "$PROJECT_NAME";<br>
Commit message: "$MESSAGE"
<br>
<br>
This is automatically generated by RoguePM
EOL
echo -e "${GREEN}[✔]${RESET} Created README.md"

mkdir -p "$PROJECT_DIR/src" "$PROJECT_DIR/include" "$PROJECT_DIR/build"

cat <<EOL > "$PROJECT_DIR/CMakeLists.txt"
cmake_minimum_required(VERSION 3.10)
project($PROJECT_NAME VERSION 0.1.0 LANGUAGES C)

set(CMAKE_C_STANDARD 11)
set(CMAKE_C_STANDARD_REQUIRED ON)

add_executable(\${PROJECT_NAME} src/main.c)
target_include_directories(\${PROJECT_NAME} PRIVATE include)
EOL
echo -e "${GREEN}[✔]${RESET} Created CMakeLists.txt"

cat <<EOL > "$PROJECT_DIR/include/${PROJECT_NAME}.h"
#ifndef ${PROJECT_NAME}_H
#define ${PROJECT_NAME}_H

void hello(void);

#endif
EOL
echo -e "${GREEN}[✔]${RESET} Created include/${PROJECT_NAME}.h"

cat <<EOL > "$PROJECT_DIR/src/main.c"
#include <stdio.h>
#include "${PROJECT_NAME}.h"

int main(void) {
    printf("Hello, $PROJECT_NAME!\\n");
    return 0;
}
EOL
echo -e "${GREEN}[✔]${RESET} Created src/main.c"

if [ -d "$FILES_DIR" ]; then
	shopt -s dotglob
	for item in "$FILES_DIR"*; do
		if [ -f "$item" ]; then
			cp "$item" "$PROJECT_DIR/"
			echo -e "${GREEN}[✔]${RESET} Created $(basename "$item")"
		elif [ -d "$item" ]; then
			cp -r "$item" "$PROJECT_DIR/"
			echo -e "${GREEN}[✔]${RESET} Created $(basename "$item") directory"
		fi
	done
	shopt -u dotglob
else
	echo "[Rogue] Additional files not found, skipping..."
fi
