#!/bin/bash
SCRIPT_DIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
FILES_DIR="$SCRIPT_DIR/files/"
PROJECT_DIR=$(pwd)/
PROJECT_NAME="placeholder"
LICENSE="mit"
MESSAGE="placeholder"

while [[ $# -gt 0 ]]; do
	case "$1" in
		-n) PROJECT_NAME="$2"; shift 2;;
		-l) LICENSE="$2"; shift 2;;
		-m) MESSAGE="$2"; shift 2;;
		*) echo "[Rogue] invalid arguments"; return 1;;
	esac
done
GREEN="\e[32m"
RESET="\e[0m"

gh api "/licenses/$LICENSE" --jq .body > "$PROJECT_DIR/LICENSE"
echo -e "${GREEN}[✔]${RESET} Created LICENSE"

cat <<EOL > "$PROJECT_DIR/README.md"
Project_Name:  "$PROJECT_NAME";<br>
Commit message: "$MESSAGE"
<br>
<br>
This is automatically generated by RoguePM
EOL
echo -e "${GREEN}[✔]${RESET} Created README.md"

cat <<EOL > "$PROJECT_DIR/go.mod"
module $PROJECT_NAME

go 1.22
EOL
echo -e "${GREEN}[✔]${RESET} Created go.mod"

mkdir -p "$PROJECT_DIR/cmd/$PROJECT_NAME"

cat <<EOL > "$PROJECT_DIR/cmd/$PROJECT_NAME/main.go"
package main

import "fmt"

func main() {
    fmt.Println("Hello, $PROJECT_NAME!")
}
EOL
echo -e "${GREEN}[✔]${RESET} Created cmd/$PROJECT_NAME/main.go"

if [ -d "$FILES_DIR" ]; then
	shopt -s dotglob
	for item in "$FILES_DIR"*; do
		if [ -f "$item" ]; then
			cp "$item" "$PROJECT_DIR/"
			echo -e "${GREEN}[✔]${RESET} Created $(basename "$item")"
		elif [ -d "$item" ]; then
			cp -r "$item" "$PROJECT_DIR/"
			echo -e "${GREEN}[✔]${RESET} Created $(basename "$item") directory"
		fi
	done
	shopt -u dotglob
else
	echo "[Rogue] Additional files not found, skipping..."
fi
