#!/bin/bash
SCRIPT_DIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
FILES_DIR="$SCRIPT_DIR/files/"
PROJECT_DIR=$(pwd)/
PROJECT_NAME="placeholder"
LICENSE="mit"
MESSAGE="placeholder"

while [[ $# -gt 0 ]]; do
	case "$1" in
		-n) PROJECT_NAME="$2"; shift 2;;
		-l) LICENSE="$2"; shift 2;;
		-m) MESSAGE="$2"; shift 2;;
		*) echo "[Rogue] invalid arguments"; return 1;;
	esac
done
GREEN="\e[32m"
RESET="\e[0m"

gh api "/licenses/$LICENSE" --jq .body > "$PROJECT_DIR/LICENSE"
echo -e "${GREEN}[✔]${RESET} Created LICENSE"

cat <<EOL > "$PROJECT_DIR/README.md"
Project_Name:  "$PROJECT_NAME";<br>
Commit message: "$MESSAGE"
<br>
<br>
This is automatically generated by RoguePM
KiCad PCB project.
EOL
echo -e "${GREEN}[✔]${RESET} Created README.md"

mkdir -p "$PROJECT_DIR/docs" "$PROJECT_DIR/fabrication"

echo -e "${GREEN}[✔]${RESET} Created project structure (open in KiCad to generate .kicad_pro/.kicad_sch/.kicad_pcb)"

if [ -d "$FILES_DIR" ]; then
	shopt -s dotglob
	for item in "$FILES_DIR"*; do
		if [ -f "$item" ]; then
			cp "$item" "$PROJECT_DIR/"
			echo -e "${GREEN}[✔]${RESET} Created $(basename "$item")"
		elif [ -d "$item" ]; then
			cp -r "$item" "$PROJECT_DIR/"
			echo -e "${GREEN}[✔]${RESET} Created $(basename "$item") directory"
		fi
	done
	shopt -u dotglob
else
	echo "[Rogue] Additional files not found, skipping..."
fi
