
FILES_DIR=~/Desktop/projects/RoguePM/templates/default/files/
PROJECT_DIR="placeholder"
PROJECT_NAME="placeholder"


#Parse arguments
while [[ $# -gt 0 ]]; do 
	case "$1" in
		-p) PROJECT_DIR="$2"; shift 2;;
		-n) PROJECT_NAME="$2"; shift 2;;
		*) echo "invalid arguments"; exit 1;; # throws when arguments other than the above two is passed
	esac
done

gh api "/licenses/mit" --jq .body > "$PROJECT_DIR/LICENSE"
echo "✔ Created LICENSE"

cat <<EOL > "$PROJECT_DIR/README.md"
"Project_Name:  "$PROJECT_NAME"

this readme is automatically generated by RoguePM
test is it working????
is it?
EOL
echo "✔ Created README.md"

# Create predefined files and directories
if [ -d $FILES_DIR ];then
	for item in $FILES_DIR*;do
		if [ -f "$item" ];then
			cp "$item" "$PROJECT_DIR/"
			echo "✔ Created $(basename "$item")" 
		elif [ -d "$item" ];then
			cp -r "$item" "$PROJECT_DIR/"
			echo "✔ Created $(basename "$item") directory" 
		fi
	done
else
	echo "Additional files not found, skipping....."
	exit 0
fi
