#!/bin/bash
SCRIPT_DIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
FILES_DIR="$SCRIPT_DIR/files/"
PROJECT_DIR=$(pwd)/
PROJECT_NAME="placeholder"
LICENSE="mit"
MESSAGE="placeholder"

while [[ $# -gt 0 ]]; do
	case "$1" in
		-n) PROJECT_NAME="$2"; shift 2;;
		-l) LICENSE="$2"; shift 2;;
		-m) MESSAGE="$2"; shift 2;;
		*) echo "[Rogue] invalid arguments"; return 1;;
	esac
done

gh api "/licenses/$LICENSE" --jq .body > "$PROJECT_DIR/LICENSE"
echo "[✔] Created LICENSE"

cat <<EOL > "$PROJECT_DIR/README.md"
Project_Name:  "$PROJECT_NAME";<br>
Commit message: "$MESSAGE"
<br>
<br>
This is automatically generated by RoguePM
Godot project.
EOL
echo "[✔] Created README.md"

cat <<EOL > "$PROJECT_DIR/project.godot"
[application]
config/name = "$PROJECT_NAME"
config/description = "Generated by RoguePM"
run/main_scene = "res://main.tscn"

[rendering]
renderer/rendering_method = "forward_plus"
EOL
echo "[✔] Created project.godot"

cat <<EOL > "$PROJECT_DIR/main.gd"
extends Node

func _ready():
	print("Hello, $PROJECT_NAME!")
EOL
echo "[✔] Created main.gd"

if [ -d "$FILES_DIR" ]; then
	shopt -s dotglob
	for item in "$FILES_DIR"*; do
		if [ -f "$item" ]; then
			cp "$item" "$PROJECT_DIR/"
			echo "[✔] Created $(basename "$item")"
		elif [ -d "$item" ]; then
			cp -r "$item" "$PROJECT_DIR/"
			echo "[✔] Created $(basename "$item") directory"
		fi
	done
	shopt -u dotglob
else
	echo "[Rogue] Additional files not found, skipping..."
fi
